sudo: required

services:
  - docker

before_install:
    - docker pull testthedocs/ttd.coala:1

script:
    - docker run -it --rm -v "${PWD}":/source:rw testthedocs/ttd.coala:1 '-c=/source/.coafile' CONTENT 

