# Site settings
title: Plone Training Portal
email: admins@plone.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://training.plone.org" # the base hostname & protocol for your site
#twitter_username: plonedocs
#github_username:  jekyll
encoding: utf-8

# Build settings
markdown: kramdown

# Dependencies
gems:
  - jekyll-lunr-js-search
  - jekyll-sitemap

# Configure search
lunr_search:
  stopwords: "stopwords.txt"
  min_length: 1

# Special kramdown settings
kramdown:
  input: GFM
  # This is important to keep the new lines in block codes.
  hard_wrap: false

# Let's not ship any of these unnecessary files
exclude:
  - Dockerfile
  - Vagrantfile
  - README.md
  - DEVELOPMENT.md
  - RELEASE.md
  - "*.sh"
  - "*.rb"
  - "*.py"
  - "*.txt"
  - "static/**/*.html"
  - "LICENSE"
  - "**/LICENSE"
  - "**/LICENSE-MIT"
  - "**/README.md"
  - "**/Readme.md"
  - "**/COPYING"
  - "**/README.md"

defaults:
  -
    scope:
      path: "content"
      type: "pages"
    values:
      layout: "content"
  -
    scope:
      path: "content/start"
      type: "pages"
    values:
      highlight_section: "start"
      category-name: start
  -
    scope:
      path: "content/trainer"
      type: "pages"
    values:
      highlight_section: "trainer"
      category-name: trainer
  -
    scope:
      path: "content/tech"
      type: "pages"
    values:
      highlight_section: "tech"
      category-name: tech
  -
    scope:
      path: "content/deployment"
      type: "pages"
    values:
      highlight_section: "deployment"
      category-name: deploy
      #attribution: Minotaur Rocket Launch at NASA Wallops by NASA Goddard Space Flight Center on Flickr, CC-BY-2.0
      #photo-link: https://www.flickr.com/photos/gsfc/5890869490/
  -
    scope:
      path: "content/blabla.md"
      type: "pages"
    values:
      url: /content/blabla.html
      layout: content
      category-name: contribute
      page: contribute
      title: Contribution Guidelines
